name: stan_env
channels:
  - conda-forge
dependencies:
  - ca-certificates=2021.10.8=h5b45459_0
  - certifi=2021.10.8=py37h03978a9_1
  - cython=0.29.25=py37hf2a7229_0
  - intel-openmp=2021.4.0=h57928b3_3556
  - libblas=3.9.0=12_win64_mkl
  - libcblas=3.9.0=12_win64_mkl
  - liblapack=3.9.0=12_win64_mkl
  - libpython=2.1=py37_0
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-ada=5.3.0=6
  - m2w64-gcc-fortran=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gcc-objc=5.3.0=6
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-make=4.1.2351.a80a8b8=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-pkg-config=0.29.1=2
  - m2w64-toolchain=5.3.0=7
  - m2w64-tools-git=5.0.0.4592.90b8472=2
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - mkl=2021.4.0=h0e2418a_729
  - msys2-conda-epoch=20160418=1
  - numpy=1.21.4=py37h940b05c_0
  - openssl=1.1.1l=h8ffe710_0
  - pip=21.2.4=py37haa95532_0
  - python=3.7.11=h6244533_0
  - python_abi=3.7=2_cp37m
  - setuptools=58.0.4=py37haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - tbb=2021.4.0=h2d74725_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py37haa95532_2
  - altair==4.1.0
  - anyio==3.4.0
  - argcomplete==1.12.3
  - argon2-cffi==21.2.0
  - argon2-cffi-bindings==21.2.0
  - asgiref==3.4.1
  - astor==0.8.1
  - attrs==21.2.0
  - backcall==0.2.0
  - backports-zoneinfo==0.2.1
  - base58==2.1.1
  - bleach==4.1.0
  - blinker==1.4
  - cachetools==4.2.4
  - cffi==1.15.0
  - charset-normalizer==2.0.9
  - click==7.1.2
  - cmdstanpy==0.9.68
  - colorama==0.4.4
  - convertdate==2.3.2
  - cycler==0.11.0
  - debugpy==1.5.1
  - decorator==5.1.0
  - defusedxml==0.7.1
  - dnspython==2.1.0
  - email-validator==1.1.3
  - entrypoints==0.3
  - ephem==4.1.2
  - fastapi==0.70.0
  - fonttools==4.28.3
  - gitdb==4.0.9
  - gitpython==3.1.24
  - h11==0.12.0
  - hijri-converter==2.2.2
  - holidays==0.11.3.1
  - httptools==0.2.0
  - idna==3.3
  - importlib-metadata==4.8.2
  - importlib-resources==5.4.0
  - ipykernel==6.6.0
  - ipython==7.30.1
  - ipython-genutils==0.2.0
  - ipywidgets==7.6.5
  - itsdangerous==2.0.1
  - jedi==0.18.1
  - jinja2==3.0.3
  - jsonschema==4.2.1
  - jupyter-client==7.1.0
  - jupyter-core==4.9.1
  - jupyterlab-pygments==0.1.2
  - jupyterlab-widgets==1.0.2
  - kiwisolver==1.3.2
  - korean-lunar-calendar==0.2.1
  - lunarcalendar==0.0.9
  - lxml==4.6.4
  - markupsafe==2.0.1
  - matplotlib==3.5.0
  - matplotlib-inline==0.1.3
  - mistune==0.8.4
  - multitasking==0.0.10
  - nbclient==0.5.9
  - nbconvert==6.3.0
  - nbformat==5.1.3
  - nest-asyncio==1.5.4
  - notebook==6.4.6
  - orjson==3.6.5
  - packaging==21.3
  - pandas==1.3.4
  - pandocfilters==1.5.0
  - parso==0.8.3
  - pickleshare==0.7.5
  - pillow==8.4.0
  - plotly==5.4.0
  - prometheus-client==0.12.0
  - prompt-toolkit==3.0.24
  - prophet==1.0.1
  - protobuf==3.19.1
  - pyarrow==6.0.1
  - pycparser==2.21
  - pydantic==1.8.2
  - pydeck==0.7.1
  - pygments==2.10.0
  - pymeeus==0.5.11
  - pympler==0.9
  - pyparsing==3.0.6
  - pyrsistent==0.18.0
  - pystan==2.19.1.1
  - python-dateutil==2.8.2
  - python-dotenv==0.19.2
  - python-multipart==0.0.5
  - pytz==2021.3
  - pytz-deprecation-shim==0.1.0.post0
  - pywin32==302
  - pywinpty==1.1.6
  - pyyaml==5.4.1
  - pyzmq==22.3.0
  - requests==2.26.0
  - send2trash==1.8.0
  - setuptools-git==1.2
  - setuptools-scm==6.3.2
  - six==1.16.0
  - smmap==5.0.0
  - sniffio==1.2.0
  - starlette==0.16.0
  - streamlit==1.2.0
  - tenacity==8.0.1
  - terminado==0.12.1
  - testpath==0.5.0
  - toml==0.10.2
  - tomli==1.2.2
  - toolz==0.11.2
  - tornado==6.1
  - tqdm==4.62.3
  - traitlets==5.1.1
  - typing-extensions==4.0.1
  - tzdata==2021.5
  - tzlocal==4.1
  - ujson==4.3.0
  - urllib3==1.26.7
  - uvicorn==0.15.0
  - validators==0.18.2
  - watchdog==2.1.6
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - websockets==10.1
  - widgetsnbextension==3.5.2
  - yfinance==0.1.67
  - zipp==3.6.0
prefix: C:\Users\raxra\anaconda3\envs\stan_env
