name: stan_env5
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - arviz=0.11.4=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - convertdate=2.4.0=pyhd8ed1ab_0
  - curl=7.81.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.24=py36h295c915_0
  - ephem=4.0.0.2=py36h27cfd23_0
  - fbprophet=0.7.1=py36h831f99a_0
  - freetype=2.10.4=h0708190_1
  - gcc_impl_linux-64=7.5.0=habd7529_20
  - gcc_linux-64=7.5.0=h47867f9_33
  - gxx_impl_linux-64=7.5.0=hd0bb8aa_20
  - gxx_linux-64=7.5.0=h555fc39_33
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.1=2
  - hijri-converter=2.2.3=pyhd8ed1ab_0
  - holidays=0.13=pyhd8ed1ab_0
  - icu=67.1=he1b5a44_0
  - jpeg=9e=h7f98852_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.3.1=py36h2531618_0
  - korean_lunar_calendar=0.2.1=pyh9f0ad1d_0
  - krb5=1.19.2=hcc1bbae_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.81.0=h2574ce0_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=7.5.0=hda03d7c_20
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran=3.0.0=1
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libgomp=11.2.0=h1d223b6_12
  - liblapack=3.9.0=13_linux64_openblas
  - libnetcdf=4.4.1.1=10
  - libnghttp2=1.46.0=hce63b2e_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=7.5.0=hb016644_20
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.11=h36c2ea0_1013
  - lunarcalendar=0.0.9=py_0
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - ncurses=6.3=h9c3ff4c_0
  - netcdf4=1.3.1=py36_1
  - numpy=1.19.5=py36hfc0c790_2
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.3=pyhd8ed1ab_0
  - pymeeus=0.5.10=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pystan=2.19.1.1=py36h7c3b610_2
  - python=3.6.13=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - scipy=1.5.3=py36h9e8f40b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.12=h27826a3_0
  - tornado=6.1=py36h8f6f2f9_1
  - pip
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xarray=0.17.0=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - pip:
    - altair==4.1.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==21.4.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - base58==2.1.1
    - bleach==4.1.0
    - blinker==1.4
    - cachetools==4.2.4
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cmdstanpy==0.9.68
    - dataclasses==0.8
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - gitdb==4.0.9
    - gitpython==3.1.20
    - idna==3.3
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.17.2
    - jinja2==3.0.3
    - jsonschema==3.2.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - lxml==4.8.0
    - markupsafe==2.0.1
    - mistune==0.8.4
    - multitasking==0.0.10
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pip==21.0
    - plotly==5.6.0
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - prophet==1.0.1
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pyarrow==6.0.1
    - pycparser==2.21
    - pydeck==0.6.2
    - pygments==2.11.2
    - pympler==1.0.1
    - pyrsistent==0.18.0
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==22.3.0
    - requests==2.27.1
    - semver==2.13.0
    - send2trash==1.8.0
    - setuptools==59.6.0
    - setuptools-git==1.2
    - smmap==5.0.0
    - streamlit==1.6.0
    - tenacity==8.0.1
    - terminado==0.12.1
    - testpath==0.6.0
    - toml==0.10.2
    - toolz==0.11.2
    - traitlets==4.3.3
    - typing-extensions==4.1.1
    - tzdata==2021.5
    - tzlocal==4.1
    - ujson==4.3.0
    - urllib3==1.26.8
    - validators==0.18.2
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
    - yfinance==0.1.70
    - zipp==3.6.0
